import type { ThemeConfig, ThemeType } from '../types';

export const THEMES: Record<ThemeType, ThemeConfig> = {
  general: {
    id: 'general',
    name: 'General',
    emoji: '🔮',
    gradient: ['#667eea', '#764ba2'],
    ballColor: '#1a1a2e',
    glowColor: '#667eea',
  },
  career: {
    id: 'career',
    name: 'Career',
    emoji: '💼',
    gradient: ['#f093fb', '#f5576c'],
    ballColor: '#2d1b3d',
    glowColor: '#f093fb',
  },
  romance: {
    id: 'romance',
    name: 'Romance',
    emoji: '💕',
    gradient: ['#fa709a', '#fee140'],
    ballColor: '#3d1b2d',
    glowColor: '#fa709a',
  },
  meme: {
    id: 'meme',
    name: 'Meme',
    emoji: '😂',
    gradient: ['#30cfd0', '#330867'],
    ballColor: '#1b1b3d',
    glowColor: '#30cfd0',
  },
  tarot: {
    id: 'tarot',
    name: 'Tarot',
    emoji: '🌙',
    gradient: ['#a8edea', '#fed6e3'],
    ballColor: '#2d2d3d',
    glowColor: '#a8edea',
  },
};

export const CLASSIC_FORTUNES: Record<ThemeType, string[]> = {
  general: [
    'It is certain',
    'Without a doubt',
    'You may rely on it',
    'As I see it, yes',
    'Most likely',
    'Outlook good',
    'Signs point to yes',
    'Reply hazy, try again',
    'Ask again later',
    'Better not tell you now',
    'Cannot predict now',
    'Concentrate and ask again',
    "Don't count on it",
    'My reply is no',
    'My sources say no',
    'Outlook not so good',
    'Very doubtful',
  ],
  career: [
    'Your skills will shine soon',
    'A promotion is in your future',
    'Network strategically today',
    'Trust your professional instincts',
    'New opportunities are coming',
    'Time to update that resume',
    'Your hard work will pay off',
    'Consider a bold career move',
    'Patience will serve you well',
    'Seek mentorship now',
    'The timing isn\'t right yet',
    'Focus on skill development',
    'Collaboration is key',
    'Your leadership is needed',
    'Don\'t settle for less',
  ],
  romance: [
    'Love is in the air',
    'Open your heart',
    'Take a chance on romance',
    'Someone special notices you',
    'Patience in love pays off',
    'Express your feelings',
    'A meaningful connection awaits',
    'Trust the timing',
    'Self-love comes first',
    'Adventure together beckons',
    'Communication is key now',
    'Keep your standards high',
    'The spark is there',
    'Give it time',
    'Your person is out there',
  ],
  meme: [
    'Big mood energy confirmed',
    'No cap, it\'s happening',
    'That\'s a vibe check passed',
    'Main character energy activated',
    'Touch grass first tbh',
    'It\'s giving yes',
    'Slay bestie',
    'Not it chief',
    'Oof level: maximum',
    'Respectfully, no',
    'Living rent free in the cosmos',
    'The universe said 👁️👄👁️',
    'Absolutely unhinged (positive)',
    'It\'s the ✨manifestation✨ for me',
    'Delulu is the solulu',
  ],
  tarot: [
    'The Fool blesses new beginnings',
    'The Tower brings transformation',
    'The Star guides you forward',
    'The Moon reveals hidden truths',
    'The Sun shines on your path',
    'Death signals rebirth',
    'The Lovers unite energies',
    'The Hermit counsels reflection',
    'The Wheel turns in your favor',
    'Strength flows through you',
    'Justice will be served',
    'Temperance brings balance',
    'The Devil tests your resolve',
    'The Magician manifests reality',
    'The High Priestess knows',
  ],
};

export const AI_SYSTEM_PROMPTS: Record<ThemeType, string> = {
  general: 'You are a mystical fortune teller. Provide a short, cryptic yet hopeful fortune (max 20 words). Be poetic and mysterious.',
  career: 'You are a career fortune teller. Give a short, professional yet inspiring career insight (max 20 words). Be strategic and motivational.',
  romance: 'You are a romantic fortune teller. Share a brief, heartfelt insight about love (max 20 words). Be warm and encouraging.',
  meme: 'You are an extremely online, Gen Z fortune teller. Give a hilarious, unhinged fortune using internet slang (max 20 words). Be chaotic and funny.',
  tarot: 'You are a tarot fortune teller. Share a mystical insight inspired by tarot symbolism (max 20 words). Be spiritual and profound.',
};
